project_id = "odnysftxwdfaujtmzerg"

[functions.create-pix-payment]
verify_jwt = false

[functions.get-mercadopago-order]
verify_jwt = true

[functions.cancel-mercadopago-order]
verify_jwt = true

[functions.resend-donation-email]
verify_jwt = true
